/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.sample;

import org.junit.Test;
import static org.junit.Assert.*;

public class SimpleHttpHandlerTest {
    @Test
    public void testDummy() {
        //assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
